spring:
  profiles:
    include: oauth
    active: prod

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    username: ${spring.datasource.username}
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secretKey: ${spring.jwt.secretKey}